### ISSUE TITLE
npm version vs. GitHub version mismatch

### ISSUE THREAD

**Issue by kuba-kubula** [iarna/run-queue#3]
Hi there,

I see there's version 2.0.0 published at npm https://www.npmjs.com/package/run-queue
But that version is not in GitHub repository, could you please publish that commit, so these two sources-of-truth are in sync?

Thanks a ton 👋

**Comment by kuba-kubula** [comment]
Also - the License text must contain copyright year, pardon for another comment.

https://choosealicense.com/licenses/isc/

**Comment by iarna** [comment]
I've pushed the tag. The lack of a year came from consultation from a lawyer with an appropriate specialty and as such I won't be changing that part.
